baseurl = "https://epinotes.netlify.com"
title = "Epi notes"
author = "Nick Griffiths"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = "UA-26007459-2"
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

enableGitInfo = true

[params]
  sitename = "Epi Notes"
  dateform = "Jan 02, 2006"

[[menu.main]]
    name = "Latest"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Index"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 4

