---
title: "How to calculate attributable fractions"
author: Nick Griffiths
date: 2020-02-16
categories:
  - Study Results
---

Attributable fractions represent the proportion of cases that happened because of a particular exposure. In other words, attributable cases would not have the outcome if they had never been exposed.

At the end of a study, we can measure the number of cases in the exposed group and the unexposed group and sort the exposed cases into an attributable group and a non-attributable group. The non-attributable cases occur at a baseline rate equal to the unexposed rate, and these are independent of the exposure. The attributable cases make up the rest.

```{r echo=FALSE}
library(ggplot2)
library(tibble)

df <- tribble(
  ~x,         ~raw, ~pct, ~w,  ~g,
  "exposed",   5,    .05,   0.3, "attributable cases",
  "exposed",   10,   0.1,   0.3, "non-attributable cases",
  "unexposed", 20,   0.1, 0.6, "non-attributable cases"
)

ggplot(df, aes(x, pct, width = w, group = factor(g), fill = factor(g))) +
  geom_col() +
  scale_y_continuous(
    breaks = c(0, 0.1, 0.15),
    labels = c("", expression(R[u]*" (10%)"),
               expression(R[e]*" (15%)"))
  ) +
  labs(x = NULL, y = "Risk", fill = NULL, title = glue::glue(
    "Cases among 100 exposed and 200 unexposed"
  )) +
  theme_minimal() +
  theme(
    panel.grid.major.x = element_blank(),    
    panel.grid.minor.y = element_blank(),
    axis.line.y.right = element_blank(),
    text = element_text(size = 14)
  ) +
  geom_text(aes(label = raw, y = c(.12, .05, .05)))
```

To calculate an attributable risk, we just calculate the risk difference, $R_e - R_u$. This represents the risk of getting the disease *due to the exposure* in the exposed group. It doesn't include people that would have gotten it regardless of their exposure.

To calculate a population attributable risk, we begin with the total risk, which includes all attributable and non-attributable cases in the population. Then we remove the non-attributable cases by subtracting the unexposed risk: $R_{total} - R_u$. This represents the risk, among the whole population, of getting the disease due to the exposure. Note that the population attributable risk is lower when the exposure is rare, but the attributable risk is the same.

The attributable fraction is the proportion of the 15 exposed cases that are attributable to the exposure ($5/15 = 33\%$), which is the same as the attributable risk divided by the exposed risk. The population attributable fraction is the proportion of all 35 cases that are attributable ($5/35 = 14.3\%$), or the population attributable risk divided by the total risk.

These measures are most useful when thinking about the impact of an intervention, since they estimate how many cases would be prevented if you completely removed the exposure.
