---
title: "Correlations"
date: 2020-03-24
author: Nick Griffiths
draft: true
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

```{r}
a1 <- function() { rnorm(100, mean = 10, sd = 5) }
a2 <- function(a1) { a1 * 3 + rnorm(100, mean = 0, sd = 20) }

b1 <- function() { rnorm(100, mean = -2, sd = 3) }
b2 <- function(b1) { b1 * 6 + rnorm(100, mean = 0, sd = 20) }

c1 <- function() { rnorm(100, mean = 100, sd = 30) }
c2 <- function(c1) { c1 + rnorm(100, mean = 0, sd = 35) }
```

```{r}
run_cors <- function() {
  a1_val <- a1()
  a2_val <- a2(a1_val)
  cora <- cor(a1_val, a2_val)

  b1_val <- b1()
  b2_val <- b2(b1_val)
  corb <- cor(b1_val, b2_val)

  c1_val <- c1()
  c2_val <- c2(c1_val)
  corc <- cor(c1_val, c2_val)

  cortot <- cor(a1_val + b1_val, a2_val + b2_val)

  sum(c(cortot > cora, cortot > corb))
}

```

```{r}
run_sim <- function () { hist(replicate(1000, run_cors())) }

run_sim()
```

The value 0 indicates the sum correlation is less than both, and the value 1 indicates it is between the `a` and `b` correlations. We see that the correlation of a sum of two random variables is biased towards values lower than each individual variable.
