---
title: "Learning to write"
date: 2020-06-28
author: Nick Griffiths
categories: Writing
---

This is the most useful thing I've ever heard about writing[^1]:

"Readers do not simply read; they interpret. Any piece of prose, no matter how short, may 'mean' in 10 (or more) different ways to 10 different readers."\
&nbsp;&nbsp; --- George Gopen and Judith Swan, [*The Science of Scientific Writing*](https://www.americanscientist.org/blog/the-long-view/the-science-of-scientific-writing)

Normally, when we learn a new skill or teach others, we focus on the specific steps we should take to accomplish the goal. Too often we don't examine what the goal is, or what prevents us from achieving it. At best, we may develop some new tools but use them incorrectly at times. At worst, we struggle to learn and eventually give up.

Gopen and Swan's article is a rare example of an article that is both easy to read and extraordinarily helpful. At first glance, it might seem like the article succeeds because of its concrete rules and clear examples. But lots of tutorials do that. What really makes it stand out is how thoroughly it defines the problem.

The authors posit that the central challenge of writing is that the reader can interpret writing in many different ways. Crucially, they don't assume this is obvious (although it is obvious to them). In the sections that follow, the authors repeatedly demonstrate concrete ways that readers can misinterpret prose. And they drive the point home by getting you to misinterpret bad prose yourself. Along the way, they propose some strategies to prevent your readers misinterpreting what you mean. But the biggest achievement of the article is not explaining the writing process, it's demonstrating what writing well actually *means*.

So, some advice for the next tutorial, presentation, or article: no learner can improve until they have a firm grasp of the problem, and that should almost always be the primary goal. Many tutorials and talks fail miserably, spending a bit of time "framing" the problem and then detailing an opinionated solution. It should be the reverse.

[^1]: Somehow I made it through high school and most of college without getting this. I've probably learned more about writing from this one article than entire English classes I had to take.
