---
title: "Checklist for project management"
date: 2022-05-02
author: Nick Griffiths
categories: Management
---

Project management is a bit of a misnomer. It sounds like a way of keeping the project on course, and moving smoothly towards a set of predefined goals. But the best project management systems promote learning and anticipate major changes, even to the fundamental aims of the project. In fact, if no changes and no learning were expected, it would be hard to see a need for project management at all. Projects could simply be planned out all in advance and executed according to the plan.

The simplest way a team learns new things is by producing a complete product and then testing it out. "Complete" can mean lots of different things: it could be a published document, a physical product, or even a simple outline of something that will be produced later. The only requirement is that it has to exist in the real world, not in someone's head. Everyone has to have access to it and be able to understand it, so that everyone can learn from it. The more often "complete" products are produced, the faster the team can learn.

In order for a team to build something and test it out, everyone must have access to lots of information about the goals of the project, the current product's status, and the work left to do. This is a checklist for organizing all that information and communication.

### Documentation

Documentation is for things that everyone will need to revisit often:

*High-level documentation of the project*. Every project should have a document that looks something like this:

- A list of fundamental values, in order of importance, which give the project a basic reason to exist and inform decisions about it
- A description of what work has already gone into the project, and why it's better than its competitors
- A list of the team's strengths, expertise and other resources
- A list of specific activities that are planned to develop the team's strengths, and to use those strengths to improve the project

*Overview of major project areas*. Include facilitators/contacts and tentative timelines.

*Project tasks*. The plan should be complete, with as much detail as possible in each project area (but at least a broad task). For all tasks:

- Assign at least one person
- Specify timeline
- Specify what earlier tasks it depends on
- Show what the status of the task is (planned, in progress, completed)

*Standards for work products*. This includes things like organizing files, data standards, templates, style guides, etc.

### Regular email updates

Regular updates are for recent changes that everyone needs to be aware of:

*Recent meeting highlights*. Short summary of what was learned or decided on that made progress towards project goals.

*Activities*. Brief summary of completed work that made progress towards project goals.

*Changes*. Any shifting goals, timeline or approach. This can include new tasks that have been identified or recent challenges that have slowed down one part of the project. It should be clear to all team members how their work is affected.

*Tentative plan*. Upcoming activities before the next regular update.

*Discussion points*. Items that should be put on the agenda for upcoming meetings.

### Meetings

Meetings should be used to discuss things, with minimal time for simple updates. The regular updates are a good way to organize an agenda for upcoming meetings.
