name: Build

on:
  push:
    branches: [ write ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.0.2'
    - uses: r-lib/actions/setup-renv@v2
      with:
        cache-version: 2
    - run: Rscript -e 'blogdown::build_site()'
